server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: choise-of-action
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver