version: '3.3'
services:
  postgres_dev:
    image: 'postgres:13.4-alpine'
    container_name: postgres_dev
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 123
  postgres_test:
    image: 'postgres:13.4-alpine'
    container_name: postgres_test
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: 123